@baseUrl= http://localhost:3333


POST {{baseUrl}}/polls
Content-Type: application/json

{
  "title": "Qual sua linguagem de programação favorita?",
  "options": ["Java", "JavaScript", "Python", "C++"]
}
###

GET {{baseUrl}}/polls/4cf73086-0485-4e43-8eb1-5a58bd554a34
###

POST {{baseUrl}}/polls/95814710-aa94-4453-a539-3f01317ab9c4/votes
Content-Type: application/json

{
  "pollOptionId": "6671e233-3401-424b-b2e1-93d601445860"
}