@baseUrl= http://localhost:3333


POST {{baseUrl}}/polls
Content-Type: application/json

{
  "title": "Qual sua linguagem de programação favorita?",
  "options": ["Java", "JavaScript", "Python", "C++"]
}
###

GET {{baseUrl}}/polls/4cf73086-0485-4e43-8eb1-5a58bd554a34
###

POST {{baseUrl}}/polls/4cf73086-0485-4e43-8eb1-5a58bd554a34/votes
Content-Type: application/json

{
  "pollOptionId": "bccc936a-b7cd-4ef2-9f9d-ad307da8f904"
}